# Form implementation generated from reading ui file 'account_create.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 720)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.517045, x2:1, y2:0.511364, stop:0 rgba(17, 21, 28, 255), stop:1 rgba(33, 45, 64, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_13 = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("background-color: transparent;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 30pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_9.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_15)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_17 = QtWidgets.QFrame(parent=self.frame_16)
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_18 = QtWidgets.QFrame(parent=self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_21 = QtWidgets.QFrame(parent=self.frame_18)
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.formLayout = QtWidgets.QFormLayout(self.frame_21)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_9)
        self.create_name = QtWidgets.QLineEdit(parent=self.frame_21)
        self.create_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.create_name.setObjectName("create_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.create_name)
        self.label_10 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_10)
        self.create_address = QtWidgets.QLineEdit(parent=self.frame_21)
        self.create_address.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.create_address.setObjectName("create_address")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.create_address)
        self.label_11 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_11)
        self.create_birthplace = QtWidgets.QLineEdit(parent=self.frame_21)
        self.create_birthplace.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.create_birthplace.setObjectName("create_birthplace")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.create_birthplace)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_12)
        self.create_birthday = QtWidgets.QLineEdit(parent=self.frame_21)
        self.create_birthday.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.create_birthday.setObjectName("create_birthday")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.create_birthday)
        self.label_13 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_13)
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_21)
        self.frame_20.setStyleSheet("background-color: transparent;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rbtn_male = QtWidgets.QRadioButton(parent=self.frame_20)
        self.rbtn_male.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.rbtn_male.setObjectName("rbtn_male")
        self.horizontalLayout_7.addWidget(self.rbtn_male)
        self.rbtn_female = QtWidgets.QRadioButton(parent=self.frame_20)
        self.rbtn_female.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.rbtn_female.setObjectName("rbtn_female")
        self.horizontalLayout_7.addWidget(self.rbtn_female)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frame_20)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_14)
        self.create_cs = QtWidgets.QLineEdit(parent=self.frame_21)
        self.create_cs.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.create_cs.setObjectName("create_cs")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.create_cs)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_15)
        self.create_ctzn = QtWidgets.QLineEdit(parent=self.frame_21)
        self.create_ctzn.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.create_ctzn.setObjectName("create_ctzn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.create_ctzn)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_16)
        self.create_email = QtWidgets.QLineEdit(parent=self.frame_21)
        self.create_email.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.create_email.setObjectName("create_email")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.create_email)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_17)
        self.create_password = QtWidgets.QLineEdit(parent=self.frame_21)
        self.create_password.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.create_password.setObjectName("create_password")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.create_password)
        self.label_18 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_18)
        self.confirm_password = QtWidgets.QLineEdit(parent=self.frame_21)
        self.confirm_password.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.confirm_password.setObjectName("confirm_password")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.confirm_password)
        self.frame_19 = QtWidgets.QFrame(parent=self.frame_21)
        self.frame_19.setStyleSheet("background-color: transparent;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_6.setSpacing(200)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.to_login = QtWidgets.QPushButton(parent=self.frame_19)
        self.to_login.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";\n"
"border-radius: 16px;\n"
"}")
        self.to_login.setObjectName("to_login")
        self.horizontalLayout_6.addWidget(self.to_login)
        self.submit_account = QtWidgets.QPushButton(parent=self.frame_19)
        self.submit_account.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}")
        self.submit_account.setObjectName("submit_account")
        self.horizontalLayout_6.addWidget(self.submit_account)
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.frame_19)
        self.verticalLayout_2.addWidget(self.frame_21)
        self.verticalLayout_17.addWidget(self.frame_18)
        self.verticalLayout_18.addWidget(self.frame_17)
        self.verticalLayout_11.addWidget(self.frame_16)
        self.verticalLayout_9.addWidget(self.frame_15)
        self.verticalLayout.addWidget(self.frame_13)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Create Account"))
        self.label_5.setText(_translate("MainWindow", "Create Account"))
        self.label_9.setText(_translate("MainWindow", "Name:"))
        self.create_name.setPlaceholderText(_translate("MainWindow", "Unang Pangalan M.I, Apelyido"))
        self.label_10.setText(_translate("MainWindow", "Address:"))
        self.create_address.setPlaceholderText(_translate("MainWindow", "Blk. XX, Lot XX"))
        self.label_11.setText(_translate("MainWindow", "Birthday:"))
        self.create_birthplace.setPlaceholderText(_translate("MainWindow", "Lugar kung saan ka pinanganak"))
        self.label_12.setText(_translate("MainWindow", "Birthplace:"))
        self.create_birthday.setPlaceholderText(_translate("MainWindow", "Ex.: 01/04/2001"))
        self.label_13.setText(_translate("MainWindow", "Sex:"))
        self.rbtn_male.setText(_translate("MainWindow", "Male"))
        self.rbtn_female.setText(_translate("MainWindow", "Female"))
        self.label_14.setText(_translate("MainWindow", "Civil Status:"))
        self.create_cs.setPlaceholderText(_translate("MainWindow", "Single/Married/Separated/Widowed"))
        self.label_15.setText(_translate("MainWindow", "Citizenship:"))
        self.create_ctzn.setPlaceholderText(_translate("MainWindow", "Ex.: Filipino, American, Chinese"))
        self.label_16.setText(_translate("MainWindow", "Email:"))
        self.create_email.setPlaceholderText(_translate("MainWindow", "Ex: cardo69420@gmail.com"))
        self.label_17.setText(_translate("MainWindow", "Password:"))
        self.create_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_18.setText(_translate("MainWindow", "Confirm Password:"))
        self.confirm_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.to_login.setText(_translate("MainWindow", "Login"))
        self.submit_account.setText(_translate("MainWindow", "Submit"))
