# Form implementation generated from reading ui file 'preview_ftjs.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(491, 327)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 468, 200))
        self.label.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.lbl_ftjsname = QtWidgets.QLabel(parent=self.frame)
        self.lbl_ftjsname.setGeometry(QtCore.QRect(6, 20, 101, 41))
        self.lbl_ftjsname.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_ftjsname.setText("")
        self.lbl_ftjsname.setObjectName("lbl_ftjsname")
        self.lbl_ftjsage = QtWidgets.QLabel(parent=self.frame)
        self.lbl_ftjsage.setGeometry(QtCore.QRect(110, 10, 41, 41))
        self.lbl_ftjsage.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_ftjsage.setText("")
        self.lbl_ftjsage.setObjectName("lbl_ftjsage")
        self.lbl_ftjsadrdress = QtWidgets.QLabel(parent=self.frame)
        self.lbl_ftjsadrdress.setGeometry(QtCore.QRect(350, 20, 111, 41))
        self.lbl_ftjsadrdress.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_ftjsadrdress.setObjectName("lbl_ftjsadrdress")
        self.lbl_ftjsyears = QtWidgets.QLabel(parent=self.frame)
        self.lbl_ftjsyears.setGeometry(QtCore.QRect(100, 60, 31, 41))
        self.lbl_ftjsyears.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_ftjsyears.setText("")
        self.lbl_ftjsyears.setObjectName("lbl_ftjsyears")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ftjs_price = QtWidgets.QLabel(parent=self.frame_2)
        self.ftjs_price.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.ftjs_price.setObjectName("ftjs_price")
        self.verticalLayout_2.addWidget(self.ftjs_price)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "I ________ , ___years of age, resident of __________\n"
"Barangay San Rafael III, City of San Jose Del Monte \n"
"Bulacan for __(years/months), availing the benefits of \n"
"Republic Act 11261, otherwise known as the \n"
"First Time Jobseekers Act of 2019, do hereby declare, \n"
"agree and undertake to abide and be bound by the \n"
"following:"))
        self.lbl_ftjsadrdress.setText(_translate("Dialog", "s"))
        self.ftjs_price.setText(_translate("Dialog", "TextLabel"))
