# Form implementation generated from reading ui file 'preview_clearance.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_clearance(object):
    def setupUi(self, dialog_clearance):
        dialog_clearance.setObjectName("dialog_clearance")
        dialog_clearance.resize(498, 542)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog_clearance)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=dialog_clearance)
        self.frame.setMinimumSize(QtCore.QSize(0, 400))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 468, 391))
        self.label.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.lbl_clrname = QtWidgets.QLabel(parent=self.frame)
        self.lbl_clrname.setGeometry(QtCore.QRect(60, 160, 211, 41))
        self.lbl_clrname.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_clrname.setText("")
        self.lbl_clrname.setObjectName("lbl_clrname")
        self.lbl_clraddress = QtWidgets.QLabel(parent=self.frame)
        self.lbl_clraddress.setGeometry(QtCore.QRect(80, 180, 211, 51))
        self.lbl_clraddress.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_clraddress.setObjectName("lbl_clraddress")
        self.lbl_clrbirthday = QtWidgets.QLabel(parent=self.frame)
        self.lbl_clrbirthday.setGeometry(QtCore.QRect(80, 210, 211, 51))
        self.lbl_clrbirthday.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_clrbirthday.setObjectName("lbl_clrbirthday")
        self.lbl_clrbirthplace = QtWidgets.QLabel(parent=self.frame)
        self.lbl_clrbirthplace.setGeometry(QtCore.QRect(140, 230, 211, 51))
        self.lbl_clrbirthplace.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_clrbirthplace.setObjectName("lbl_clrbirthplace")
        self.lbl_clrsex = QtWidgets.QLabel(parent=self.frame)
        self.lbl_clrsex.setGeometry(QtCore.QRect(50, 250, 211, 51))
        self.lbl_clrsex.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_clrsex.setObjectName("lbl_clrsex")
        self.lbl_clrcivilstatus = QtWidgets.QLabel(parent=self.frame)
        self.lbl_clrcivilstatus.setGeometry(QtCore.QRect(110, 280, 211, 51))
        self.lbl_clrcivilstatus.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_clrcivilstatus.setObjectName("lbl_clrcivilstatus")
        self.lbl_clrcitizenship = QtWidgets.QLabel(parent=self.frame)
        self.lbl_clrcitizenship.setGeometry(QtCore.QRect(100, 300, 211, 51))
        self.lbl_clrcitizenship.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_clrcitizenship.setObjectName("lbl_clrcitizenship")
        self.lbl_clrpurpose = QtWidgets.QLabel(parent=self.frame)
        self.lbl_clrpurpose.setGeometry(QtCore.QRect(100, 350, 211, 51))
        self.lbl_clrpurpose.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lbl_clrpurpose.setObjectName("lbl_clrpurpose")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=dialog_clearance)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.clearance_price = QtWidgets.QLabel(parent=self.frame_2)
        self.clearance_price.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.clearance_price.setObjectName("clearance_price")
        self.verticalLayout_2.addWidget(self.clearance_price)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_clearance)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(dialog_clearance)
        self.buttonBox.accepted.connect(dialog_clearance.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_clearance.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_clearance)

    def retranslateUi(self, dialog_clearance):
        _translate = QtCore.QCoreApplication.translate
        dialog_clearance.setWindowTitle(_translate("dialog_clearance", "Dialog"))
        self.label.setText(_translate("dialog_clearance", "To Whom It May Concern\n"
"\n"
"This is to certify that the person whose name, signature \n"
"and thumb mark print below has requested a Record \n"
"Clearance from this office and the result(s) is/are listed \n"
"below.\n"
"\n"
"Name: \n"
"Address: \n"
"Birthday: \n"
"BIRTHPLACE: \n"
"SEX:\n"
"Civil Status: \n"
"Citizenship: \n"
"Remarks: NO DEROGATORY RECORDS\n"
"PURPOSE: "))
        self.lbl_clraddress.setText(_translate("dialog_clearance", "s"))
        self.lbl_clrbirthday.setText(_translate("dialog_clearance", "s"))
        self.lbl_clrbirthplace.setText(_translate("dialog_clearance", "s"))
        self.lbl_clrsex.setText(_translate("dialog_clearance", "s"))
        self.lbl_clrcivilstatus.setText(_translate("dialog_clearance", "s"))
        self.lbl_clrcitizenship.setText(_translate("dialog_clearance", "s"))
        self.lbl_clrpurpose.setText(_translate("dialog_clearance", "s"))
        self.clearance_price.setText(_translate("dialog_clearance", "TextLabel"))
