# Form implementation generated from reading ui file 'reference.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_ref(object):
    def setupUi(self, dialog_ref):
        dialog_ref.setObjectName("dialog_ref")
        dialog_ref.resize(507, 115)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../FinalsProject/app_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dialog_ref.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(dialog_ref)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=dialog_ref)
        self.label.setStyleSheet("font: 40pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lbl_ref = QtWidgets.QLabel(parent=dialog_ref)
        self.lbl_ref.setStyleSheet("font: 40pt \"Times New Roman\";")
        self.lbl_ref.setObjectName("lbl_ref")
        self.horizontalLayout.addWidget(self.lbl_ref)

        self.retranslateUi(dialog_ref)
        QtCore.QMetaObject.connectSlotsByName(dialog_ref)

    def retranslateUi(self, dialog_ref):
        _translate = QtCore.QCoreApplication.translate
        dialog_ref.setWindowTitle(_translate("dialog_ref", "Reference #"))
        self.label.setText(_translate("dialog_ref", "Reference #:"))
        self.lbl_ref.setText(_translate("dialog_ref", "asdasd"))
