# Form implementation generated from reading ui file 'ui_home.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_kiosk_window(object):
    def setupUi(self, kiosk_window):
        kiosk_window.setObjectName("kiosk_window")
        kiosk_window.resize(1118, 824)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/san_rafael3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        kiosk_window.setWindowIcon(icon)
        kiosk_window.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.517045, x2:1, y2:0.511364, stop:0 rgba(17, 21, 28, 255), stop:1 rgba(33, 45, 64, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=kiosk_window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainframe = QtWidgets.QFrame(parent=self.page_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainframe.sizePolicy().hasHeightForWidth())
        self.mainframe.setSizePolicy(sizePolicy)
        self.mainframe.setStyleSheet("background-color: transparent;")
        self.mainframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainframe.setObjectName("mainframe")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainframe)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.mainframe)
        self.frame_3.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_logout = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_logout.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icons/home_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_logout.setIcon(icon1)
        self.btn_logout.setIconSize(QtCore.QSize(50, 50))
        self.btn_logout.setObjectName("btn_logout")
        self.horizontalLayout_2.addWidget(self.btn_logout)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.frame_7)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_4.addWidget(self.lcdNumber, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(parent=self.mainframe)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(179, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(750, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../doc_processing_kiosk/logo.png"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 30pt \"Times New Roman\";")
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.frame_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.btn_request = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_request.setGeometry(QtCore.QRect(90, 20, 231, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_request.sizePolicy().hasHeightForWidth())
        self.btn_request.setSizePolicy(sizePolicy)
        self.btn_request.setStyleSheet("QPushButton{\n"
"    font: 25 15pt \"Roboto Light\";\n"
"    background-color: rgb(229, 228, 226);\n"
"font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_request.setObjectName("btn_request")
        self.btn_about = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_about.setGeometry(QtCore.QRect(480, 20, 231, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_about.sizePolicy().hasHeightForWidth())
        self.btn_about.setSizePolicy(sizePolicy)
        self.btn_about.setStyleSheet("QPushButton{\n"
"background-color: rgb(229, 228, 226);\n"
"    font: 25 15pt \"Roboto Light\";\n"
"font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_about.setObjectName("btn_about")
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout_3.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(179, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.mainframe)
        self.stackedWidget.addWidget(self.page_home)
        self.select_doc = QtWidgets.QWidget()
        self.select_doc.setObjectName("select_doc")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.select_doc)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_9 = QtWidgets.QFrame(parent=self.select_doc)
        self.frame_9.setStyleSheet("background-color: transparent;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 30pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_6.addWidget(self.frame_10, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_9)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 500))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(112, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(750, 0))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout.setHorizontalSpacing(75)
        self.gridLayout.setVerticalSpacing(50)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_ftjsOath = QtWidgets.QPushButton(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ftjsOath.sizePolicy().hasHeightForWidth())
        self.btn_ftjsOath.setSizePolicy(sizePolicy)
        self.btn_ftjsOath.setStyleSheet("QPushButton{\n"
"    font: 25 18pt \"Roboto Light\";\n"
"    background-color: rgb(229, 228, 226);\n"
"font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_ftjsOath.setObjectName("btn_ftjsOath")
        self.gridLayout.addWidget(self.btn_ftjsOath, 0, 0, 1, 1)
        self.btn_permit = QtWidgets.QPushButton(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_permit.sizePolicy().hasHeightForWidth())
        self.btn_permit.setSizePolicy(sizePolicy)
        self.btn_permit.setStyleSheet("QPushButton{\n"
"    font: 25 18pt \"Roboto Light\";\n"
"    background-color: rgb(229, 228, 226);\n"
"font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_permit.setObjectName("btn_permit")
        self.gridLayout.addWidget(self.btn_permit, 0, 1, 1, 1)
        self.btn_clearance = QtWidgets.QPushButton(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clearance.sizePolicy().hasHeightForWidth())
        self.btn_clearance.setSizePolicy(sizePolicy)
        self.btn_clearance.setStyleSheet("QPushButton{\n"
"    font: 25 16pt \"Roboto Light\";\n"
"    background-color: rgb(229, 228, 226);\n"
"font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_clearance.setObjectName("btn_clearance")
        self.gridLayout.addWidget(self.btn_clearance, 1, 0, 1, 1)
        self.btn_certificate = QtWidgets.QPushButton(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_certificate.sizePolicy().hasHeightForWidth())
        self.btn_certificate.setSizePolicy(sizePolicy)
        self.btn_certificate.setStyleSheet("QPushButton{\n"
"    font: 25 14pt \"Roboto Light\";\n"
"    background-color: rgb(229, 228, 226);\n"
"font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_certificate.setObjectName("btn_certificate")
        self.gridLayout.addWidget(self.btn_certificate, 1, 1, 1, 1)
        self.btn_editacc = QtWidgets.QPushButton(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_editacc.sizePolicy().hasHeightForWidth())
        self.btn_editacc.setSizePolicy(sizePolicy)
        self.btn_editacc.setStyleSheet("QPushButton{\n"
"    font: 25 16pt \"Roboto Light\";\n"
"    background-color: rgb(229, 228, 226);\n"
"font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_editacc.setObjectName("btn_editacc")
        self.gridLayout.addWidget(self.btn_editacc, 2, 0, 1, 1)
        self.btn_indigency = QtWidgets.QPushButton(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_indigency.sizePolicy().hasHeightForWidth())
        self.btn_indigency.setSizePolicy(sizePolicy)
        self.btn_indigency.setStyleSheet("QPushButton{\n"
"    font: 25 18pt \"Roboto Light\";\n"
"    background-color: rgb(229, 228, 226);\n"
"font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_indigency.setObjectName("btn_indigency")
        self.gridLayout.addWidget(self.btn_indigency, 2, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_12)
        spacerItem3 = QtWidgets.QSpacerItem(112, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.verticalLayout_8.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.select_doc)
        self.edit_acc = QtWidgets.QWidget()
        self.edit_acc.setObjectName("edit_acc")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.edit_acc)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_39 = QtWidgets.QFrame(parent=self.edit_acc)
        self.frame_39.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_39.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_39.setStyleSheet("background-color: transparent;")
        self.frame_39.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_39.setObjectName("frame_39")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_39)
        self.horizontalLayout_16.setContentsMargins(100, 0, 100, 9)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btn_home2_5 = QtWidgets.QPushButton(parent=self.frame_39)
        self.btn_home2_5.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        self.btn_home2_5.setIcon(icon1)
        self.btn_home2_5.setIconSize(QtCore.QSize(50, 50))
        self.btn_home2_5.setObjectName("btn_home2_5")
        self.horizontalLayout_16.addWidget(self.btn_home2_5)
        self.btn_toRequest_6 = QtWidgets.QPushButton(parent=self.frame_39)
        self.btn_toRequest_6.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./icons/document_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_toRequest_6.setIcon(icon2)
        self.btn_toRequest_6.setIconSize(QtCore.QSize(50, 50))
        self.btn_toRequest_6.setObjectName("btn_toRequest_6")
        self.horizontalLayout_16.addWidget(self.btn_toRequest_6)
        self.verticalLayout_12.addWidget(self.frame_39)
        self.frame_24 = QtWidgets.QFrame(parent=self.edit_acc)
        self.frame_24.setStyleSheet("background-color: transparent;")
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_12.addWidget(self.frame_24)
        self.frame_13 = QtWidgets.QFrame(parent=self.edit_acc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("background-color: transparent;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 30pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_9.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_15)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_17 = QtWidgets.QFrame(parent=self.frame_16)
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_18 = QtWidgets.QFrame(parent=self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_21 = QtWidgets.QFrame(parent=self.frame_18)
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.formLayout = QtWidgets.QFormLayout(self.frame_21)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_9)
        self.edit_name = QtWidgets.QLineEdit(parent=self.frame_21)
        self.edit_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.edit_name.setObjectName("edit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_name)
        self.label_10 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_10)
        self.edit_address = QtWidgets.QLineEdit(parent=self.frame_21)
        self.edit_address.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.edit_address.setObjectName("edit_address")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_address)
        self.label_11 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_11)
        self.edit_birthday = QtWidgets.QLineEdit(parent=self.frame_21)
        self.edit_birthday.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.edit_birthday.setObjectName("edit_birthday")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_birthday)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_12)
        self.edit_birthplace = QtWidgets.QLineEdit(parent=self.frame_21)
        self.edit_birthplace.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.edit_birthplace.setObjectName("edit_birthplace")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_birthplace)
        self.label_13 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_13)
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_21)
        self.frame_20.setStyleSheet("background-color: transparent;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rbtn_male = QtWidgets.QRadioButton(parent=self.frame_20)
        self.rbtn_male.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.rbtn_male.setObjectName("rbtn_male")
        self.horizontalLayout_7.addWidget(self.rbtn_male)
        self.rbtn_female = QtWidgets.QRadioButton(parent=self.frame_20)
        self.rbtn_female.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.rbtn_female.setObjectName("rbtn_female")
        self.horizontalLayout_7.addWidget(self.rbtn_female)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frame_20)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_14)
        self.edit_cs = QtWidgets.QLineEdit(parent=self.frame_21)
        self.edit_cs.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.edit_cs.setObjectName("edit_cs")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_cs)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_15)
        self.edit_ctzn = QtWidgets.QLineEdit(parent=self.frame_21)
        self.edit_ctzn.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.edit_ctzn.setObjectName("edit_ctzn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_ctzn)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_16)
        self.edit_email = QtWidgets.QLineEdit(parent=self.frame_21)
        self.edit_email.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.edit_email.setObjectName("edit_email")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_email)
        self.label_19 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_19)
        self.edit_password = QtWidgets.QLineEdit(parent=self.frame_21)
        self.edit_password.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";")
        self.edit_password.setObjectName("edit_password")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_password)
        self.frame_19 = QtWidgets.QFrame(parent=self.frame_21)
        self.frame_19.setStyleSheet("background-color: transparent;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_6.setSpacing(200)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.clear_ca = QtWidgets.QPushButton(parent=self.frame_19)
        self.clear_ca.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";\n"
"border-radius: 16px;\n"
"}")
        self.clear_ca.setObjectName("clear_ca")
        self.horizontalLayout_6.addWidget(self.clear_ca)
        self.submit_ca = QtWidgets.QPushButton(parent=self.frame_19)
        self.submit_ca.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}")
        self.submit_ca.setObjectName("submit_ca")
        self.horizontalLayout_6.addWidget(self.submit_ca)
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frame_19)
        self.verticalLayout_19.addWidget(self.frame_21)
        self.verticalLayout_17.addWidget(self.frame_18)
        self.verticalLayout_18.addWidget(self.frame_17)
        self.verticalLayout_11.addWidget(self.frame_16)
        self.verticalLayout_9.addWidget(self.frame_15)
        self.verticalLayout_12.addWidget(self.frame_13)
        self.stackedWidget.addWidget(self.edit_acc)
        self.about_page = QtWidgets.QWidget()
        self.about_page.setObjectName("about_page")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.about_page)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_42 = QtWidgets.QFrame(parent=self.about_page)
        self.frame_42.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_42.setStyleSheet("background-color: transparent;")
        self.frame_42.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_42.setObjectName("frame_42")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_42)
        self.horizontalLayout_17.setContentsMargins(100, 0, 100, 9)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btn_home2_6 = QtWidgets.QPushButton(parent=self.frame_42)
        self.btn_home2_6.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        self.btn_home2_6.setIcon(icon1)
        self.btn_home2_6.setIconSize(QtCore.QSize(50, 50))
        self.btn_home2_6.setObjectName("btn_home2_6")
        self.horizontalLayout_17.addWidget(self.btn_home2_6)
        self.btn_toRequest_7 = QtWidgets.QPushButton(parent=self.frame_42)
        self.btn_toRequest_7.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        self.btn_toRequest_7.setIcon(icon2)
        self.btn_toRequest_7.setIconSize(QtCore.QSize(50, 50))
        self.btn_toRequest_7.setObjectName("btn_toRequest_7")
        self.horizontalLayout_17.addWidget(self.btn_toRequest_7)
        self.verticalLayout_28.addWidget(self.frame_42)
        self.frame_41 = QtWidgets.QFrame(parent=self.about_page)
        self.frame_41.setMinimumSize(QtCore.QSize(0, 700))
        self.frame_41.setStyleSheet("background-color: transparent;")
        self.frame_41.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_41)
        self.label_18.setMinimumSize(QtCore.QSize(0, 0))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 30pt \"Times New Roman\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_27.addWidget(self.label_18)
        self.verticalLayout_28.addWidget(self.frame_41)
        self.stackedWidget.addWidget(self.about_page)
        self.form_indigency = QtWidgets.QWidget()
        self.form_indigency.setObjectName("form_indigency")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.form_indigency)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_25 = QtWidgets.QFrame(parent=self.form_indigency)
        self.frame_25.setStyleSheet("background-color:transparent;")
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_26 = QtWidgets.QFrame(parent=self.frame_25)
        self.frame_26.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_28 = QtWidgets.QFrame(parent=self.frame_26)
        self.frame_28.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_28.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_10.setContentsMargins(100, 0, 100, 9)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_home2_2 = QtWidgets.QPushButton(parent=self.frame_28)
        self.btn_home2_2.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        self.btn_home2_2.setIcon(icon1)
        self.btn_home2_2.setIconSize(QtCore.QSize(50, 50))
        self.btn_home2_2.setObjectName("btn_home2_2")
        self.horizontalLayout_10.addWidget(self.btn_home2_2)
        self.btn_toRequest_2 = QtWidgets.QPushButton(parent=self.frame_28)
        self.btn_toRequest_2.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        self.btn_toRequest_2.setIcon(icon2)
        self.btn_toRequest_2.setIconSize(QtCore.QSize(50, 50))
        self.btn_toRequest_2.setObjectName("btn_toRequest_2")
        self.horizontalLayout_10.addWidget(self.btn_toRequest_2)
        self.verticalLayout_15.addWidget(self.frame_28)
        self.verticalLayout_14.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(parent=self.frame_25)
        self.frame_27.setMinimumSize(QtCore.QSize(0, 700))
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem4 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_16.addItem(spacerItem4)
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_27)
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_22)
        self.formLayout_2.setContentsMargins(100, -1, 100, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_22)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.cBox_indigency = QtWidgets.QComboBox(parent=self.frame_22)
        self.cBox_indigency.setStyleSheet("\n"
"#cBox_indigency QAbstractItemView{\n"
"selection-background-color: rgb(72, 82, 101);\n"
"}\n"
"#cBox_indigency::drop-down{\n"
"border: 0px;\n"
"}\n"
"QComboBox{\n"
"border: 4px;\n"
"color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"}\n"
"#cBox_indigency:on{\n"
"border: 4px solid rgb(72, 82, 101);\n"
"}\n"
"#cBox_indigency QListView{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.cBox_indigency.setObjectName("cBox_indigency")
        self.cBox_indigency.addItem("")
        self.cBox_indigency.addItem("")
        self.cBox_indigency.addItem("")
        self.cBox_indigency.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cBox_indigency)
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_22)
        self.frame_23.setStyleSheet("background-color: transparent;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_8.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout_8.setSpacing(200)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.clear_idg = QtWidgets.QPushButton(parent=self.frame_23)
        self.clear_idg.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";\n"
"border-radius: 16px;\n"
"}")
        self.clear_idg.setObjectName("clear_idg")
        self.horizontalLayout_8.addWidget(self.clear_idg)
        self.submit_idg = QtWidgets.QPushButton(parent=self.frame_23)
        self.submit_idg.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}")
        self.submit_idg.setObjectName("submit_idg")
        self.horizontalLayout_8.addWidget(self.submit_idg)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.frame_23)
        self.verticalLayout_16.addWidget(self.frame_22)
        spacerItem5 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_16.addItem(spacerItem5)
        self.verticalLayout_14.addWidget(self.frame_27)
        self.verticalLayout_13.addWidget(self.frame_25)
        self.stackedWidget.addWidget(self.form_indigency)
        self.form_bp = QtWidgets.QWidget()
        self.form_bp.setObjectName("form_bp")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.form_bp)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_29 = QtWidgets.QFrame(parent=self.form_bp)
        self.frame_29.setStyleSheet("background-color: transparent;")
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(20)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_31 = QtWidgets.QFrame(parent=self.frame_29)
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_12.setContentsMargins(100, 0, 100, 95)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btn_home2 = QtWidgets.QPushButton(parent=self.frame_31)
        self.btn_home2.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        self.btn_home2.setIcon(icon1)
        self.btn_home2.setIconSize(QtCore.QSize(50, 50))
        self.btn_home2.setObjectName("btn_home2")
        self.horizontalLayout_12.addWidget(self.btn_home2)
        self.btn_toRequest_3 = QtWidgets.QPushButton(parent=self.frame_31)
        self.btn_toRequest_3.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        self.btn_toRequest_3.setIcon(icon2)
        self.btn_toRequest_3.setIconSize(QtCore.QSize(50, 50))
        self.btn_toRequest_3.setObjectName("btn_toRequest_3")
        self.horizontalLayout_12.addWidget(self.btn_toRequest_3)
        self.verticalLayout_20.addWidget(self.frame_31)
        self.label_22 = QtWidgets.QLabel(parent=self.frame_29)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 24pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_20.addWidget(self.label_22)
        self.bp_bname = QtWidgets.QLineEdit(parent=self.frame_29)
        self.bp_bname.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 24pt \"Helvetica Neue\";")
        self.bp_bname.setObjectName("bp_bname")
        self.verticalLayout_20.addWidget(self.bp_bname)
        self.label_23 = QtWidgets.QLabel(parent=self.frame_29)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 24pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_20.addWidget(self.label_23)
        self.bp_badress = QtWidgets.QLineEdit(parent=self.frame_29)
        self.bp_badress.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 24pt \"Helvetica Neue\";")
        self.bp_badress.setText("")
        self.bp_badress.setObjectName("bp_badress")
        self.verticalLayout_20.addWidget(self.bp_badress)
        self.frame_30 = QtWidgets.QFrame(parent=self.frame_29)
        self.frame_30.setStyleSheet("background-color: transparent;")
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_11.setSpacing(200)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.clear_bp = QtWidgets.QPushButton(parent=self.frame_30)
        self.clear_bp.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";\n"
"border-radius: 16px;\n"
"}")
        self.clear_bp.setObjectName("clear_bp")
        self.horizontalLayout_11.addWidget(self.clear_bp)
        self.submit_bp = QtWidgets.QPushButton(parent=self.frame_30)
        self.submit_bp.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}")
        self.submit_bp.setObjectName("submit_bp")
        self.horizontalLayout_11.addWidget(self.submit_bp)
        self.verticalLayout_20.addWidget(self.frame_30)
        self.verticalLayout_21.addWidget(self.frame_29, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.stackedWidget.addWidget(self.form_bp)
        self.form_clearance = QtWidgets.QWidget()
        self.form_clearance.setObjectName("form_clearance")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.form_clearance)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_34 = QtWidgets.QFrame(parent=self.form_clearance)
        self.frame_34.setStyleSheet("background-color: transparent;")
        self.frame_34.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_35 = QtWidgets.QFrame(parent=self.frame_34)
        self.frame_35.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_35.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_37 = QtWidgets.QFrame(parent=self.frame_35)
        self.frame_37.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btn_home2_3 = QtWidgets.QPushButton(parent=self.frame_37)
        self.btn_home2_3.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        self.btn_home2_3.setIcon(icon1)
        self.btn_home2_3.setIconSize(QtCore.QSize(50, 50))
        self.btn_home2_3.setObjectName("btn_home2_3")
        self.horizontalLayout_14.addWidget(self.btn_home2_3)
        self.btn_toRequest_4 = QtWidgets.QPushButton(parent=self.frame_37)
        self.btn_toRequest_4.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        self.btn_toRequest_4.setIcon(icon2)
        self.btn_toRequest_4.setIconSize(QtCore.QSize(50, 50))
        self.btn_toRequest_4.setObjectName("btn_toRequest_4")
        self.horizontalLayout_14.addWidget(self.btn_toRequest_4)
        self.verticalLayout_24.addWidget(self.frame_37)
        self.verticalLayout_23.addWidget(self.frame_35)
        self.frame_36 = QtWidgets.QFrame(parent=self.frame_34)
        self.frame_36.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        spacerItem6 = QtWidgets.QSpacerItem(20, 260, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_25.addItem(spacerItem6)
        self.frame_32 = QtWidgets.QFrame(parent=self.frame_36)
        self.frame_32.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_32.setObjectName("frame_32")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_32)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_32)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"background-color:transparent;")
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_17)
        self.cBox_clearance = QtWidgets.QComboBox(parent=self.frame_32)
        self.cBox_clearance.setStyleSheet("#cBox_clearance QAbstractItemView{\n"
"selection-background-color: rgb(72, 82, 101);\n"
"}\n"
"#cBox_clearance::drop-down{\n"
"border: 0px;\n"
"}\n"
"QComboBox{\n"
"border: 4px;\n"
"color: rgb(255, 255, 255);\n"
"    font: 16pt \"Helvetica Neue\";\n"
"}\n"
"#cBox_clearance:on{\n"
"border: 4px solid rgb(72, 82, 101);\n"
"}\n"
"#cBox_clearance QListView{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.cBox_clearance.setObjectName("cBox_clearance")
        self.cBox_clearance.addItem("")
        self.cBox_clearance.addItem("")
        self.cBox_clearance.addItem("")
        self.cBox_clearance.addItem("")
        self.cBox_clearance.addItem("")
        self.cBox_clearance.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cBox_clearance)
        self.frame_33 = QtWidgets.QFrame(parent=self.frame_32)
        self.frame_33.setStyleSheet("background-color: transparent;")
        self.frame_33.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_13.setSpacing(200)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.clear_bc = QtWidgets.QPushButton(parent=self.frame_33)
        self.clear_bc.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";\n"
"border-radius: 16px;\n"
"}")
        self.clear_bc.setObjectName("clear_bc")
        self.horizontalLayout_13.addWidget(self.clear_bc)
        self.submit_bc = QtWidgets.QPushButton(parent=self.frame_33)
        self.submit_bc.setStyleSheet("QPushButton{\n"
"background-color: rgb(109, 125, 153);\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}")
        self.submit_bc.setObjectName("submit_bc")
        self.horizontalLayout_13.addWidget(self.submit_bc)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.frame_33)
        self.verticalLayout_25.addWidget(self.frame_32)
        spacerItem7 = QtWidgets.QSpacerItem(20, 259, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_25.addItem(spacerItem7)
        self.verticalLayout_23.addWidget(self.frame_36)
        self.verticalLayout_22.addWidget(self.frame_34)
        self.stackedWidget.addWidget(self.form_clearance)
        self.form_ftjs = QtWidgets.QWidget()
        self.form_ftjs.setObjectName("form_ftjs")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.form_ftjs)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_40 = QtWidgets.QFrame(parent=self.form_ftjs)
        self.frame_40.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_40.setStyleSheet("background-color: transparent;")
        self.frame_40.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_home2_4 = QtWidgets.QPushButton(parent=self.frame_40)
        self.btn_home2_4.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        self.btn_home2_4.setIcon(icon1)
        self.btn_home2_4.setIconSize(QtCore.QSize(50, 50))
        self.btn_home2_4.setObjectName("btn_home2_4")
        self.horizontalLayout_15.addWidget(self.btn_home2_4)
        self.btn_toRequest_5 = QtWidgets.QPushButton(parent=self.frame_40)
        self.btn_toRequest_5.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"color: white;\n"
"font: 20pt \"Segoe UI\";border-radius: 16px;\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(89, 120, 142);\n"
"transform: scale(0.98); \n"
"box-shadow: 3px 2px 22px 1px rgba(0, 0, 0, 0.24); \n"
"\n"
"}\n"
"")
        self.btn_toRequest_5.setIcon(icon2)
        self.btn_toRequest_5.setIconSize(QtCore.QSize(50, 50))
        self.btn_toRequest_5.setObjectName("btn_toRequest_5")
        self.horizontalLayout_15.addWidget(self.btn_toRequest_5)
        self.verticalLayout_26.addWidget(self.frame_40)
        self.frame_38 = QtWidgets.QFrame(parent=self.form_ftjs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_38.sizePolicy().hasHeightForWidth())
        self.frame_38.setSizePolicy(sizePolicy)
        self.frame_38.setStyleSheet("background-color: transparent;")
        self.frame_38.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_38.setObjectName("frame_38")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_38)
        self.formLayout_4.setObjectName("formLayout_4")
        self.btn_years = QtWidgets.QPushButton(parent=self.frame_38)
        self.btn_years.setStyleSheet("QPushButton{\n"
"background-color: rgb(229, 228, 226);\n"
"    font: 25 15pt \"Roboto Light\";\n"
"font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_years.setObjectName("btn_years")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btn_years)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_38)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 30pt \"Times New Roman\";\n"
"background-color:transparent;\n"
"")
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.frame_38)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 30pt \"Times New Roman\";\n"
"background-color:transparent;\n"
"")
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.line_editage = QtWidgets.QLineEdit(parent=self.frame_38)
        self.line_editage.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"")
        self.line_editage.setText("")
        self.line_editage.setObjectName("line_editage")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editage)
        self.line_editstay = QtWidgets.QLineEdit(parent=self.frame_38)
        self.line_editstay.setStyleSheet("    color: rgb(255, 255, 255);\n"
"    font: 22pt \"Helvetica Neue\";\n"
"    \n"
"")
        self.line_editstay.setText("")
        self.line_editstay.setObjectName("line_editstay")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_editstay)
        self.verticalLayout_26.addWidget(self.frame_38)
        self.stackedWidget.addWidget(self.form_ftjs)
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.stackedWidget.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.stackedWidget)
        kiosk_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(kiosk_window)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(kiosk_window)
        self.lcdNumber.setDigitCount(8)
        timer = QtCore.QTimer(kiosk_window)
        timer.timeout.connect(self.showlcd)
        timer.start(1000)
        self.showlcd()

    def showlcd(self):
            time = QtCore.QTime.currentTime()
            text = time.toString('hh:mm')
            self.lcdNumber.display(text)
    def retranslateUi(self, kiosk_window):
        _translate = QtCore.QCoreApplication.translate
        kiosk_window.setWindowTitle(_translate("kiosk_window", "Document Processing"))
        self.btn_logout.setText(_translate("kiosk_window", "Log Out"))
        self.label_2.setText(_translate("kiosk_window", "Barangay San Rafael III\n"
"Kiosk Document Processing"))
        self.btn_request.setText(_translate("kiosk_window", "Request Document"))
        self.btn_about.setText(_translate("kiosk_window", "About"))
        self.label_4.setText(_translate("kiosk_window", "Choose Document you want to Request"))
        self.btn_ftjsOath.setText(_translate("kiosk_window", "Job Seeker Oath"))
        self.btn_permit.setText(_translate("kiosk_window", "Business Permit"))
        self.btn_clearance.setText(_translate("kiosk_window", "Barangay Clearance"))
        self.btn_certificate.setText(_translate("kiosk_window", "Job Seeker Certificate"))
        self.btn_editacc.setText(_translate("kiosk_window", "Edit Account Info"))
        self.btn_indigency.setText(_translate("kiosk_window", "Indigency"))
        self.btn_home2_5.setText(_translate("kiosk_window", "Home"))
        self.btn_toRequest_6.setText(_translate("kiosk_window", "Request Different Document"))
        self.label_5.setText(_translate("kiosk_window", "Edit Account Info"))
        self.label_9.setText(_translate("kiosk_window", "Name:"))
        self.edit_name.setPlaceholderText(_translate("kiosk_window", "Unang Pangalan M.I, Apelyido"))
        self.label_10.setText(_translate("kiosk_window", "Address:"))
        self.edit_address.setPlaceholderText(_translate("kiosk_window", "Blk. XX, Lot XX"))
        self.label_11.setText(_translate("kiosk_window", "Birthday:"))
        self.edit_birthday.setPlaceholderText(_translate("kiosk_window", "Ex.: 01/04/2001"))
        self.label_12.setText(_translate("kiosk_window", "Birthplace:"))
        self.edit_birthplace.setPlaceholderText(_translate("kiosk_window", "Lugar kung saan ka pinanganak"))
        self.label_13.setText(_translate("kiosk_window", "Sex:"))
        self.rbtn_male.setText(_translate("kiosk_window", "Male"))
        self.rbtn_female.setText(_translate("kiosk_window", "Female"))
        self.label_14.setText(_translate("kiosk_window", "Civil Status:"))
        self.edit_cs.setPlaceholderText(_translate("kiosk_window", "Single/Married/Separated/Widowed"))
        self.label_15.setText(_translate("kiosk_window", "Citizenship:"))
        self.edit_ctzn.setPlaceholderText(_translate("kiosk_window", "Ex.: Filipino, American, Chinese"))
        self.label_16.setText(_translate("kiosk_window", "Email:"))
        self.edit_email.setPlaceholderText(_translate("kiosk_window", "Ex: cardo69420@gmail.com"))
        self.label_19.setText(_translate("kiosk_window", "Password:"))
        self.edit_password.setPlaceholderText(_translate("kiosk_window", "New Password"))
        self.clear_ca.setText(_translate("kiosk_window", "Clear"))
        self.submit_ca.setText(_translate("kiosk_window", "Submit"))
        self.btn_home2_6.setText(_translate("kiosk_window", "Home"))
        self.btn_toRequest_7.setText(_translate("kiosk_window", "Request Different Document"))
        self.label_18.setText(_translate("kiosk_window", "About App\n"
"\n"
"Lorem Ipsum is an app that uses Anonymous and Incognito."))
        self.btn_home2_2.setText(_translate("kiosk_window", "Home"))
        self.btn_toRequest_2.setText(_translate("kiosk_window", "Request Different Document"))
        self.label_6.setText(_translate("kiosk_window", "Purpose:"))
        self.cBox_indigency.setItemText(0, _translate("kiosk_window", "Click here to Select"))
        self.cBox_indigency.setItemText(1, _translate("kiosk_window", "Educational Assistance"))
        self.cBox_indigency.setItemText(2, _translate("kiosk_window", "Medical Assistance"))
        self.cBox_indigency.setItemText(3, _translate("kiosk_window", "Financial Assistance"))
        self.clear_idg.setText(_translate("kiosk_window", "Clear"))
        self.submit_idg.setText(_translate("kiosk_window", "Submit"))
        self.btn_home2.setText(_translate("kiosk_window", "Home"))
        self.btn_toRequest_3.setText(_translate("kiosk_window", "Request Different Document"))
        self.label_22.setText(_translate("kiosk_window", "Business Name:"))
        self.bp_bname.setPlaceholderText(_translate("kiosk_window", "Pangalan ng Business"))
        self.label_23.setText(_translate("kiosk_window", "Business Address:"))
        self.bp_badress.setPlaceholderText(_translate("kiosk_window", "Address ng iyong business"))
        self.clear_bp.setText(_translate("kiosk_window", "Clear"))
        self.submit_bp.setText(_translate("kiosk_window", "Submit"))
        self.btn_home2_3.setText(_translate("kiosk_window", "Home"))
        self.btn_toRequest_4.setText(_translate("kiosk_window", "Request Different Document"))
        self.label_17.setText(_translate("kiosk_window", "Purpose:"))
        self.cBox_clearance.setItemText(0, _translate("kiosk_window", "Click here to Select"))
        self.cBox_clearance.setItemText(1, _translate("kiosk_window", "Local Employment"))
        self.cBox_clearance.setItemText(2, _translate("kiosk_window", "Police Clearance"))
        self.cBox_clearance.setItemText(3, _translate("kiosk_window", "Motor Loan"))
        self.cBox_clearance.setItemText(4, _translate("kiosk_window", "Bank Requirements"))
        self.cBox_clearance.setItemText(5, _translate("kiosk_window", "Loan"))
        self.clear_bc.setText(_translate("kiosk_window", "Clear"))
        self.submit_bc.setText(_translate("kiosk_window", "Submit"))
        self.btn_home2_4.setText(_translate("kiosk_window", "Home"))
        self.btn_toRequest_5.setText(_translate("kiosk_window", "Request Different Document"))
        self.btn_years.setText(_translate("kiosk_window", "Enter"))
        self.label_7.setText(_translate("kiosk_window", "Years Stayed:"))
        self.label_8.setText(_translate("kiosk_window", "Age:"))
        self.line_editage.setPlaceholderText(_translate("kiosk_window", "Age"))
        self.line_editstay.setPlaceholderText(_translate("kiosk_window", "Years of stay in San Rafael III"))
